### ISSUE TITLE
The arista restore doesn't change the startup configuration unless I modify a task in the validated collection.

### ISSUE THREAD

**Issue by andubiel** [KB-perByte/network.restore#8]
##### SUMMARY

The arista restore doesn't change the startup configuration. I needed to modify the tasks in the validated collection ```
```roles/run/includes/cli_restore/eos.yaml``` to see my changes to the arista routers restored from backups and actually change the startup config.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

These tasks didn't seem to work so I commented them off and replaced with a task that works.
network.restore
roles/run/includes/cli_restore/eos.yaml

The proposed fix
```
---
#- name: Read backed-up configuration file
#  ansible.builtin.slurp:
#    src: "{{ network_restore_backup_path }}"
#  register: backedup_config

#- name: Apply backed-up configuration
#  arista.eos.eos_config:
#    lines: "{{ backedup_config.content | b64decode }}"

- name: Restore the config
  arista.eos.eos_config:
    replace: config
    src: "{{ network_restore_backup_path }}"
    save_when: always
```

##### ANSIBLE VERSION

```paste below
ansible-core                         2.15.6
```

##### COLLECTION VERSION

```paste below
network.backup            2.0.0  
network.base              5.0.0  
network.restore           1.0.0  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

arista.eos.eos

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

```
TASK [network.restore.run : Invoke restore operation] **************************
included: /usr/share/ansible/collections/ansible_collections/network/restore/roles/run/includes/cli_restore/eos.yaml for rtr2, rtr4
TASK [network.restore.run : Restore the config] ********************************
changed: [rtr4]
changed: [rtr2]
```

##### ACTUAL RESULTS

The existing tasks doesn't change the arista router's startup config.

```paste below
TASK [network.restore.run : Read backed-up configuration file] *****************
ok: [rtr4]
ok: [rtr2]
TASK [network.restore.run : Apply backed-up configuration] *********************
ok: [rtr2]
ok: [rtr4]
```
